language: c

compiler:
  - gcc
  - clang

before_install: 
  - 'wget http://download.guardtime.com/libgt-0.3.12.tar.gz -O - | tar xfz - && cd libgt-0.3.12 &&  ./configure --silent --prefix=/usr && make && sudo make install && cd ..'


script: 
  - autoreconf -vi
  - ./configure
  - make
  - make check
